# After changing this file, check it on:
#   http://lint.travis-ci.org/

os:         linux
language:   python

python:
    - 3.6

env:
    matrix:
        - PYQUIL_VERSION=1.9.0
        - PYQUIL_VERSION=2.1.0

matrix:
    include:
        - os: linux
          language: python
          python:   2.7
          env:      PYQUIL_VERSION=1.9.0
        - os: osx
          language: generic
          python:   2.7
          env:      WANTED_PYTHON_VERSION=2.7 PYQUIL_VERSION=1.9.0
        - os: osx
          language: generic
          python:   3.6
          env:      WANTED_PYTHON_VERSION=3.6 PYQUIL_VERSION=1.9.0
        - os: osx
          language: generic
          python:   3.6
          env:      WANTED_PYTHON_VERSION=3.6 PYQUIL_VERSION=2.1.0

before_install:
    - |
        if [ $TRAVIS_OS_NAME == "osx" ]; then
            if [ "0" == "1" ]; then
                brew update                                                         # this swaps python versions and makes 3 the default one

                if [ "$WANTED_PYTHON_VERSION" == "2.7" ]; then
                    brew reinstall python\@2 || brew link --overwrite python\@2     # install and link python2 and pip2 to /usr/local/bin
                    export PATH=/usr/local/opt/python\@2/bin:$PATH
                    export PYTHON_EXE=python
                else
                    brew reinstall python                                           # install and link python3 and pip3 to /usr/local/bin
                    export PATH=/usr/local/opt/python/bin:$PATH
                    export PYTHON_EXE=python3
                fi
            fi

            export PYTHON_EXE=python
            export CK_PLATFORM_NAME="generic-macos "                            # used later by CK
        else
            sudo apt-get update -qq
            sudo apt-get install python-pip
            export WANTED_PYTHON_VERSION=$TRAVIS_PYTHON_VERSION                 # since Python is supported in Linux, get it from Travis
            export CK_PLATFORM_NAME="generic-linux "                            # used later by CK (note the trailing space to make the choice unique)
            export PYTHON_EXE=python
        fi

install:
    - CWD=`pwd`
    - THIS_REPO_NAME=`basename $CWD`
    - echo "os=${TRAVIS_OS_NAME}, python=${WANTED_PYTHON_VERSION}, pyquil_version=${PYQUIL_VERSION}"
    - which ${PYTHON_EXE}
    - ${PYTHON_EXE} --version
    - ${PYTHON_EXE} -m pip install --ignore-installed --verbose pip setuptools          # make sure pip is also up to date no matter what
    - ${PYTHON_EXE} -m pip install ck
    - ck pull repo:${THIS_REPO_NAME}                                                    # trigger pulling dependent repositories
    - echo "$CK_PLATFORM_NAME" | ck detect platform.os --update_platform_init           # set the platform to generic-linux (1) or generic-macos (2)
    - echo | ck detect soft:compiler.python --default_selection="$WANTED_PYTHON_VERSION" --first_match
    - PYTHON_FILE=`ck virtual env --tags=compiler,python --shell_cmd='echo $CK_ENV_COMPILER_PYTHON_FILE'`
    - echo ${PYTHON_FILE}
    - ${PYTHON_FILE} --version
    - ${PYTHON_FILE} -m pip install --ignore-installed --verbose pip setuptools
    - ck install package:lib-python-scipy
    - ck install package:lib-pyquil-multiversion --force_version=$PYQUIL_VERSION        # select a specific version out of a "multiversion" package

script:
    - ck run program:pyquil-demo --cmd_key=from-quil-file --env.QUIL_FILE=../teleport.quil --treat_return_code_as_exit_code
    - ck run program:pyquil-demo --cmd_key=from-pyquil-examples --env.PYQUIL_EXAMPLE=meyer_penny_game.py --treat_return_code_as_exit_code
    - ck run program:rigetti-vqe --env.VQE_MAX_ITERATIONS=10 --treat_return_code_as_exit_code

notifications:
    email:
        on_success: always
        on_failure: always

